spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/metafy
    username: app_admin
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
jwt:
  secret: J1FKivsYXVX1sVsV+K==IFPB==MONTEIRO==ads=eh=top==R/0Fs0tLJqHsK8a3OT3hC/WZo=
  expirationMs: 1800000
server:
  port: 8080

main:
  allow-bean-definition-overriding: true
test:
  cache:
    enable: false